version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myuser -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    networks:
      - backend
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  chromadb:
    image: chromadb/chroma:0.4.24
    restart: always
    ports:
      - "8001:8000"
    volumes:
      - chroma_data:/chroma/chroma
    networks:
      - backend
    # Bez healthchecka — ChromaDB startuje wolno, restart: always wystarczy

  web:
    build: ./backend
    working_dir: /code
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/code
      - media_data:/code/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: "supersecretkey"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CHROMA_HOST: "chromadb"
      CHROMA_PORT: "8000"
    networks:
      - backend

  celery_worker:
    build: ./backend
    working_dir: /code
    command: celery -A app worker --loglevel=info
    volumes:
      - ./backend:/code
      - media_data:/code/media
      - hf_cache:/root/.cache/huggingface
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      chromadb:
        condition: service_started
    environment:
      DB_NAME: mydb
      DB_USER: myuser
      DB_PASSWORD: mypassword
      DB_HOST: db
      DB_PORT: 5432
      DJANGO_SECRET_KEY: "supersecretkey"
      CELERY_BROKER_URL: "redis://redis:6379/0"
      CELERY_RESULT_BACKEND: "redis://redis:6379/0"
      CHROMA_HOST: "chromadb"
      CHROMA_PORT: "8000"
      EMBEDDING_MODEL: "paraphrase-multilingual-MiniLM-L12-v2"
    networks:
      - backend

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - backend

  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://localhost:8000/api/users/
    ports:
      - "5173:5173"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
    depends_on:
      - web
    networks:
      - backend

volumes:
  postgres_data:
  media_data:
  chroma_data:
  hf_cache:

networks:
  backend:
    driver: bridge