# Generated by Django 5.0 on 2026-05-06 13:19

import documents.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('index', models.PositiveIntegerField(help_text='Kolejność chunku w dokumencie')),
                ('text', models.TextField()),
                ('char_count', models.PositiveIntegerField()),
                ('chunk_type', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['index'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to=documents.models.document_upload_path)),
                ('original_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('txt', 'TXT')], max_length=10)),
                ('file_size', models.PositiveIntegerField(help_text='Rozmiar w bajtach')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzanie'), ('ready', 'Gotowy'), ('error', 'Błąd')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('embedding_status', models.CharField(choices=[('none', 'Brak'), ('chunking', 'Chunking'), ('embedding', 'Generowanie embeddingów'), ('done', 'Gotowe'), ('error', 'Błąd')], default='none', max_length=20)),
                ('embedding_error', models.TextField(blank=True, default='')),
                ('chunk_type', models.CharField(default='sentence', help_text='fixed | sentence', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
